### ISSUE TITLE
[feature request]: FEM minimal example problem/test

### ISSUE THREAD

**Issue by jorgepz** [JuliaIntervals/IntervalLinearAlgebra.jl#102]
## Feature description
A minimal working example of the package functions applied to a linear static FEM problem. I offer myself as contributor!

 - [x] add a fixed-parameter truss example
 - [x] add a interval-parameter truss example

**Comment by lucaferranti** [comment]
that's a great idea and timing is also very good as I should have a PR with a first PILS solver interface coming in a week or so. In the small test I crafted it was applied to a 7-bar truss structure which had uncertainty on the stiffness of one bar (not sure if the resulting linear system was obtained with FEM or some other discretization) It's example 4.1 of the attached paper.

[skalna2006.pdf](https://github.com/JuliaIntervals/IntervalLinearAlgebra.jl/files/7271616/skalna2006.pdf)

That (or maybe even better the more interesting 2D example you had sent marcelo) would add great value to the package!

**Comment by jorgepz** [comment]
Excellent. 👍🏼 

I could start writing down that example for the documentation.

Regarding the example, yes, the matrix `K(p)` is the same that is obtained using FEM.

Moreover, the matrix `K(p)` is  a sum of 7 matrices each one multiplied by a stiffness s_{ij}. It would be helpful to explicitly write these matrices in the documentation, since they correspond the matrices `Ai` .... in the current PILS structure, as I understand it, the 6 matrices with fixed stiffnesses would sum the `A0`, and the `A1` would be multiplied by the interval stiffness `s_{23}`.
