### ISSUE TITLE
video not correctly embedded in documentation

### ISSUE THREAD

**Issue by lucaferranti** [JuliaIntervals/IntervalLinearAlgebra.jl#92]
see here: https://juliaintervals.github.io/IntervalLinearAlgebra.jl/dev/

I think the problem is in how Documenter manipulates the `@raw html` block in the documentation

**Comment by mforets** [comment]
did you try changing `height="315"`?

**Comment by lucaferranti** [comment]
yep, but it didn't help. Also, the settings here (height=315) is the same used [here](https://juliaintervals.github.io/pages/explanations/videos/), where the video is displayed correctly.

**Comment by lucaferranti** [comment]
related issue: https://github.com/JuliaDocs/Documenter.jl/issues/1701
