### ISSUE TITLE
is the current CI an overkill

### ISSUE THREAD

**Issue by lucaferranti** [JuliaIntervals/IntervalLinearAlgebra.jl#96]
Currently the CI is testing on all main OS (windows, linux, macos) and on both 64 and 32 bits architecture (32 bits not for macos), for latest stable and nightly, giving in total 3*2*2 - 1= 11 checks plus the documentation.

I wonder whether this is necessary or whether it is an overkill. Maybe test just 3 OS and 64 bits (latest and nightly)? 

cc @mforets @dpsanders

**Comment by mforets** [comment]
testing on all main OS and the current stable julia release is the minimum. also adding the LTS version to CI is good (but the ecosystem has moved from v1.0, so maybe wait for the next LTS :) ).

i don't have an opinion about also adding a test for the nightly julia version and on 32 bits architectures. also note that the tests run in parallel and in < 10mins (just checked https://github.com/JuliaIntervals/IntervalLinearAlgebra.jl/pull/94).
